### PR TITLE
249

### LINKED ISSUE #249: TestPriorityMutex fails under `go test -race`
**Describe the bug**
The Go race detector finds a race condition when running `TestPriorityMutex`.

**To Reproduce**
`go test -race ./utils`

**Expected behavior**
No race condition found.

### PR DESCRIPTION
**Pull request by raghavsharma873**
Fixes #249  .

### Solution
Don't rely on `time.Sleep` since there are no formal guarantees
Instead use a WaitGroup-based wrapper so we can properly assert that all goroutines
have asked for lock

### CODE REVIEW

File: utils/priority_mutex_test.go [hunk 1]
```diff
@@ -16,17 +16,41 @@ package utils
...
+func newWrappedPriorityMutex(numLockCalls int) *wrappedPriorityMutex {
+	w := &wrappedPriorityMutex{PriorityMutex: new(PriorityMutex)}
+	w.lockWg.Add(numLockCalls)
+	return w
+}
+
+func (w *wrappedPriorityMutex) Lock(priority bool) {
+	c := w.PriorityMutex.lockInternal(priority)
+	w.lockWg.Done()
+	w.wait(c)
```
Comment (septerr) [inline utils/priority_mutex_test.go:43]: In this method, if we do following, I think we can initialize the WaitGroup counter with 60 instead of 61. 60 will make the test easier to understand. lmk what you think. 🙏 
```
func (w *wrappedPriorityMutex) Lock(priority bool) {
	c := w.PriorityMutex.lockInternal(priority)
        if c != nil {
          w.lockWg.Done()
	  w.wait(c)
        }
}
```

**Review by septerr — APPROVED** [review]
🎉

**Comment by raghavsharma873** [comment]
I don't have write access to this repo so I can't merge. Feel free to merge on my behalf. I'm requesting access
